export const MetaTagSEOData = [
  // Home = 0
  {
    tab: "Home",
    description: "",
    keywords: [
      "CSRA Indoor Services",
      "Augusta Landscaping",
      "Augusta plumbing",
      "Augusta Irrigation",
      "Evans landscaping",
      "Evans irrigation",
      "Evans plumbing",
      "drip irrigation",
      "sprinkler system installation",
      "irrigation repair",
      "smart irrigation",
      "irrigation maintenance",
      "indoor plumbing",
      "plumbing repair",
      "leak detection",
      "pipe installation",
      "toilet repair",
      "water heater installation",
      "drain cleaning",
      "outdoor landscaping",
      "landscape design",
      "hardscaping",
      "lawn care",
      "garden design",
      "yard maintenance",
      "tree trimming",
      "retaining wall construction",
      "block wall installation",
      "stone retaining walls",
      "retaining wall repair",
      "decorative retaining walls",
      "retaining wall drainage",
    ],
    socialTitle: "GeorgiaLina - Home",
    socialDescription: "",
  },
  //   irrigation = 1
  {
    tab: "Irrigation",
    description: "",
    keywords: [
      "drip irrigation",
      "sprinkler system installation",
      "irrigation repair",
      "smart irrigation",
      "irrigation maintenance",
      "outdoor irrigation",
      "lawn sprinklers",
      "garden irrigation",
      "drip system maintenance",
      "irrigation system design",
      "irrigation consultation",
    ],
    socialTitle: "GeorgiaLina - Home",
    socialDescription: "",
  },
  //   landscaping = 2
  {
    tab: "Landscaping",
    description: "",
    keywords: [
      "outdoor landscaping",
      "landscape design",
      "hardscaping",
      "lawn care",
      "garden design",
      "yard maintenance",
      "tree trimming",
    ],
    socialTitle: "GeorgiaLina - Home",
    socialDescription: "",
  },
  //   Plumbing = 3
  {
    tab: "Plumbing",
    description: "",
    keywords: [
      "indoor plumbing",
      "plumbing repair",
      "leak detection",
      "pipe installation",
      "toilet repair",
      "water heater installation",
      "drain cleaning",
    ],
    socialTitle: "GeorgiaLina - Home",
    socialDescription: "",
  },
  //   retaining Wall = 4
  {
    tab: "Retaining Wall",
    description: "",
    keywords: [
      "retaining wall construction",
      "block wall installation",
      "stone retaining walls",
      "retaining wall repair",
      "decorative retaining walls",
      "retaining wall drainage",
    ],
    socialTitle: "GeorgiaLina - Home",
    socialDescription: "",
  },
  //   Contact Us = 5
  {
    tab: "Contact Us",
    description: "",
    keywords: ["Augusta,", "Evans", "Grovetown", "Appling", "CSRA"],
    socialTitle: "GeorgiaLina - Home",
    socialDescription: "",
  },
];
