[build]
  command = "npm run build"
  publish = "out"
  functions = "out/functions"

[build.environment]
  NODE_VERSION = "14"

[[plugins]]
  package = "@netlify/plugin-next"

[dev]
  command = "npm run dev"
