[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"


[[plugins]]
  package = "@netlify/plugin-next"

[dev]
  command = "npm run dev"
